[package]
name = "epicinium"
version = "0.1.0"
authors = ["Sander in 't Veld <sanderintveld@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
rlimit = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_urlencoded = "*"
serde_repr = "*"
serde_plain = "*"
enumset = { version = "1.0", features = ["serde"] }
vec-drain-where = "*"
rand = "0.7.0"
reqwest = { version = "*", features = ["json"] }
futures = "^0.3.5"
tokio = { version = "0.2", features = ["rt-threaded", "macros", "time", "sync", "tcp", "signal", "fs", "io-util", "process"] }
backtrace = "*"
libc = "*"
log = "*"
fern = { version = "^0.6", features = ["reopen-03"] }
chrono = "*"
thread-id = "*"
itertools = "*"
unindent = "*"

[features]
defaults = ["increase-sockets"]

candidate = []
version-is-dev = []
increase-sockets = []
