[package]
name = "epicinium"
version = "0.1.0"
authors = ["Sander in 't Veld <sanderintveld@hotmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_repr = "*"
enum-map = "*"
enum-map-derive = "*"
enumset = "*"
signal-hook = {version = "0.1.10", features = ["tokio-support"] }
vec-drain-where = "*"
rand = "0.7.0"
openssl = "*"
reqwest = "*"
futures = "0.1"
tokio = "0.1"
tokio-io = "0.1"
backtrace = "*"
owning_ref = "*"

[features]
defaults = []

candidate = []
version-is-dev = []
