[package]
name = "epicinium"
version = "0.1.0"
authors = ["Sander in 't Veld <sanderintveld@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
rlimit = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_urlencoded = "*"
serde_repr = "*"
serde_plain = "*"
enum-map = "*"
enum-map-derive = "*"
enumset = { version = "1.0", features = ["serde"] }
vec-drain-where = "*"
rand = "0.7.0"
openssl = "*"
reqwest = { version = "*", features = ["json"] }
futures = "0.3"
tokio = { version = "0.2", features = ["rt-threaded", "macros", "time", "sync", "tcp", "signal", "fs", "io-util"] }
backtrace = "*"
owning_ref = "*"
libc = "*"

[features]
defaults = []

candidate = []
version-is-dev = []
