[package]
name = "epicinium"
version = "0.1.0"
authors = ["Sander in 't Veld <sanderintveld@hotmail.com>"]

[dependencies]
serde = "*"
serde_derive = "*"
serde_json = "*"
enum-map = "*"
enum-map-derive = "*"
signal-hook = "0.1.10"
vec-drain-where = "*"
rand = "0.7.0"

[features]
defaults = []
candidate = []
